version: "3.3"
   
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    networks:
      midas:


  backend:
    build: 
      context: .
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=sparkar.settings.local
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=True
    volumes:
      - .:/code
    ports:
      - "8081:8080"
    networks:
      midas:
    depends_on:
      - db

  
networks:
  midas:
    driver: bridge