# Generated by Django 3.2.7 on 2022-04-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, default='', max_length=100)),
                ('lastName', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(blank=True, default='', max_length=100)),
                ('org', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('contact', models.CharField(blank=True, default='', max_length=100)),
                ('currentEng', models.CharField(blank=True, default='', max_length=100)),
                ('linkedIn', models.CharField(blank=True, default='', max_length=100)),
                ('fbUrl', models.CharField(blank=True, default='', max_length=100)),
                ('commitWeeklyTime', models.CharField(blank=True, default='', max_length=100)),
                ('progRating', models.CharField(blank=True, default='', max_length=100)),
                ('takenWorkshopsInPast', models.CharField(blank=True, default='', max_length=100)),
                ('whatToLearn', models.CharField(blank=True, default='', max_length=100)),
                ('whySelectMe', models.TextField(blank=True, default='', max_length=5000)),
                ('whyArDev', models.TextField(blank=True, default='', max_length=5000)),
                ('devCircle', models.CharField(blank=True, default='', max_length=100)),
                ('githubId', models.CharField(blank=True, default='', max_length=100)),
                ('personalWebsite', models.CharField(blank=True, default='', max_length=100)),
                ('experience', models.CharField(blank=True, default='', max_length=100)),
                ('is_shortlisted', models.BooleanField(default=False)),
            ],
        ),
    ]
