# Generated by Django 3.2.7 on 2022-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='devote_time_for_advanced',
            field=models.CharField(blank=True, default='1plus', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='done_commercial_project',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='effects_created',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='experienced_in',
            field=models.CharField(blank=True, default='Coding Skills', max_length=150),
        ),
        migrations.AddField(
            model_name='applicant',
            name='having_idea_about_ar_vr',
            field=models.CharField(blank=True, default='1plus', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='laptopn_w_min_requirements',
            field=models.CharField(blank=True, default='1plus', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='most_suitable_job_description',
            field=models.CharField(blank=True, default='Graphic designer', max_length=150),
        ),
        migrations.AddField(
            model_name='applicant',
            name='other_ar_tools',
            field=models.CharField(blank=True, default='1plus', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rate_coding_ability',
            field=models.CharField(blank=True, default='I have a basic understanding of coding principles', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='sparkar_effects_created',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='sparkar_portfolio',
            field=models.CharField(blank=True, default='1plus', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='target_filter_types',
            field=models.CharField(blank=True, default='1plus', max_length=30),
        ),
        migrations.AddField(
            model_name='applicant',
            name='used_designing_tool',
            field=models.CharField(blank=True, default='1plus', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='used_photoshop_or_blender',
            field=models.CharField(blank=True, default='1plus', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='why_did_learn_or_are_interested_in_ar',
            field=models.CharField(blank=True, default='1plus', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='years_of_exp_in_sparkar',
            field=models.CharField(blank=True, default='1plus', max_length=20),
        ),
    ]
