# Generated by Django 3.2.7 on 2022-04-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220421_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rate_coding_ability',
            field=models.CharField(blank=True, default='I have a basic understanding of coding principles', max_length=500),
        ),
    ]
