# Generated by Django 3.2.7 on 2022-04-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220421_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='devote_time_for_advanced',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='having_idea_about_ar_vr',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='laptop_w_min_requirements',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='other_ar_tools',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sparkar_portfolio',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='target_filter_types',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='used_designing_tool',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='used_photoshop_or_blender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='why_did_learn_or_are_interested_in_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
