# Generated by Django 3.2.7 on 2022-04-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220422_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='why_learn_or_are_inwhy_learn_or_are_interested_in_arterested_in_ar',
            new_name='why_interested_in_ar',
        ),
    ]
